"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _chat_message from './chat-message.bones.json'

configureBoneyard({"color":"#f1f5f9","animate":"shimmer"})

registerBones({
  "chat-message": _chat_message,
})
